#!/bin/bash
# Deploy to Koyeb - European Platform

echo "🚀 Koyeb Deployment"
echo "==================="
echo ""
echo "Koyeb offers free container hosting!"
echo ""
echo "FREE TIER:"
echo "✅ 1 free service"
echo "✅ 512MB RAM"
echo "✅ Auto-scaling"
echo "✅ Global edge network"
echo ""
echo "DEPLOYMENT STEPS:"
echo "1. Go to https://koyeb.com"
echo "2. Sign up with GitHub"
echo "3. Create new app"
echo "4. Connect GitHub repository"
echo "5. Use Dockerfile.web"
echo "6. Deploy!"
echo ""
echo "Your app will be at:"
echo "https://shift-web-your-org.koyeb.app"
