name: Build and Upload .deb

on:
  push:
    tags:
      - 'v*'  # Trigger only on tagged versions like v1.0.0
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-python python3-all python3-setuptools build-essential

      - name: Build .deb
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ../shift_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
